blank_issues_enabled: false
contact_links:
  - name: Have a feature suggestion?
    url: https://github.com/ole-scout/roadmap/discussions/categories/ideas
    about: Have an idea for a feature? Start a discussion in ideas!
  - name: Have a question?
    url: https://github.com/ole-scout/roadmap/discussions/categories/q-a
    about: Check out Q&A discussions for an existing answer, or create a question.
  - name: Need something specific to your needs?
    url: https://ole-scout.com
    about: Contact our sales team using the contact form on our website.
